package com.example.domain;

public enum ContentValidationStatus {
  RECEIVED, DETECTING, NLP, VALIDATING_TEXT, VALIDATING_LOGO, VALIDATING_ENTERPRISE, AGGREGATING, AWAITING_REVIEW, ROUTING, COMPLETED, FAILED
}