akka.javasdk.agent {

  model-provider = openai

  openai {
    model-name = "gpt-4o-mini"
    api-key = ${?OPENAI_API_KEY}
  }

}

akka.javasdk.agent.guardrails {

  "prompt-injection-guard" {
    class = "akka.javasdk.agent.SimilarityGuard"
    agent-roles = ["*"]
    category = PROMPT_INJECTION
    use-for = ["model-request"]
    report-only = false
    threshold = 0.75
    bad-examples-resource-dir = "guardrail/jailbreak"
  }

  "pii-guard" {
    class = "com.example.application.guardrail.PiiGuard"
    agent-roles = ["*"]
    category = PII
    use-for = ["model-request"]
    report-only = false
  }

}